### ISSUE TITLE
Add multi denotation chars

### ISSUE THREAD

**Issue by komxvl** [afry/quill-mention#108]
It's possible to add multiDenotationChars, like this: mentionDenotationChars: ["{{", "#"]. Support two symbols '{{'

**Comment by NeonCreativeStudios** [comment]
This would also benefit myself, as I plan on using Quill to edit Twig templates which uses **{{** and **{%**

**Comment by komxvl** [comment]
Any updates? Dear @NeonCreativeStudios, how could you resolve this issue?

**Comment by rajshivam** [comment]
Was facing similar requirement, reference for the pull request :+1:  #114 
Let me know if it works.

**Comment by NeonCreativeStudios** [comment]
Could you kindly build quill.mention.min.js in the dist directory? Using the source file doesn't work for me as I'm not using css loader with my webpack. Then I'd be happy to test it

**Comment by rajshivam** [comment]
@NeonCreativeStudios have build quill.mention.min.js in dist directory. You can test it now.

**Comment by NeonCreativeStudios** [comment]
I tried it with both 1 and 2 character denotations and only noticed a small problem:

The third argument passed to the source function (the mention character that was used) is always 1 character long even if it's a multi denotation character.

And similarly the denotation character stored in the HTML element, delta and retrieved using getContents() is also 1 character long, in this case it should be "{{" but is "{"

![image](https://user-images.githubusercontent.com/49883221/69480087-257ba000-0dfc-11ea-8c9a-ede679f07241.png)

**Comment by rajshivam** [comment]
Thanks for the insightful testing, have implemented the changes, please retest.

**Comment by NeonCreativeStudios** [comment]
Hi. Yes for me it works great now.
I've tested typing to add them, and also getContents() and setContents()

**Comment by komxvl** [comment]
Great,thnx, but some [conflicts](https://github.com/afconsult/quill-mention/pull/114 ) :(

**Comment by NeonCreativeStudios** [comment]
Those 2 conflicting files shouldn't get merged. I'm responsible for him changing the minified file, oops!

**Comment by komxvl** [comment]
Hi. Any news?

**Comment by rajshivam** [comment]
@komxvl @NeonCreativeStudios  I've resolved the conflicts.

**Comment by komxvl** [comment]
Thanks @rajshivam. @MadSpindel could you please merge PR

**Comment by MadSpindel** [comment]
This works in version 2.2.3 now.
