### ISSUE TITLE
Problem with rollup

### ISSUE THREAD

**Issue by MeloJR** [afry/quill-mention#111]
Hi,

I am using this plugin for a custom element and I would like to build this element with rollup as a **es module**. I have build the module but when I use the module in the browser, the module breaks because `require is not defined`.
I have search a bit on google and I have found that it occurs when `import/export` and `require` are mixing in the same file. I have found that the line which breaks the bundle is this:

```
const numberIsNaN = require('./imports/numberisnan.js');
```

I have modified that line in my working copy with the following line
```
import numberIsNaN from './imports/numberisnan.js';
```
and it works perfectly.

I would like to know if there is some reason to use require in that line instead import. For now I will use a modified version of this code in order to fix my bundle.

**Comment by MadSpindel** [comment]
@MeloJR I have changed from Webpack to Rollup for Quill Mention now. Please try the latest version 2.2.1 👍
