### ISSUE TITLE
Bug: Value and denotationChar undefined when editing

### ISSUE THREAD

**Issue by maciekstosio** [afry/quill-mention#119]
Hi,
I've just added quill-mention to project, by adding:

```
import 'quill-mention'
import 'quill-mention/dist/quill.mention.min.css'

...

    formats = [
        'header', 'font', 'size',
        'bold', 'italic', 'underline', 'strike', 'blockquote',
        'list', 'bullet', 'indent',
        'link', 'image', 'mention',
    ]

...

mention: {
            mentionDenotationChars: ['@'],
            isolateCharacter: false,
            source: function (searchTerm, renderList, mentionChar) {
                const atValues = [
                    { "id": "515fd775-cb54-41f3-b921-56163871e2cf", "value": "Mickey Dooley", "link": "http://google.pl", "denotationChar": "@"},
                    { "id": "3f0b7933-57b8-4d9d-b238-f8af62b2e945", "value": "Desmond Waterstone" },
                    { "id": "711f68ab-ca20-4011-ab0f-d98c8fac4c05", "value": "Jeralee Fryd" },
                    { "id": "775e05fc-72bc-48a1-9508-5c61674734f1", "value": "Eddie Hucquart" },
                    { "id": "e8701885-105e-4a21-b200-98e559776655", "value": "Nathalia Whear" }
                ];
                console.log('source', searchTerm, renderList, mentionChar)
                renderList(atValues)
            },
        },

```

And adding work great:

![image](https://user-images.githubusercontent.com/11800297/70528976-c03fe280-1b4f-11ea-8b00-9e1ffd070faf.png)

But when I trying to edit, I'm getting undefined:

![image](https://user-images.githubusercontent.com/11800297/70528997-ce8dfe80-1b4f-11ea-9d80-007cf4027be0.png)

Is there something that I'm missing?

quill-mention: 2.2.1
react-quill: 1.3.3

**Comment by maciekstosio** [comment]
Hi, after further investigation I realised that problem was on our API - we stripped HTML tags from all attributes other than class.

**Comment by luknl** [comment]
@maciekstosio, We had the same issue, and were using a ruby gem to sanitize content. We fixed it by adding the following data attributes in the whitelist: "data-value", "data-index", "data-denotation-char", "data-id", "data-link"
