### ISSUE TITLE
Quill mention not working with react quill and no css

### ISSUE THREAD

**Issue by a-utkarsh** [afry/quill-mention#125]
Here is the link of my code sandbox.
https://codesandbox.io/embed/react-quill-demo-cxro7?fontsize=14&hidenavigation=1&theme=dark

**Comment by phatv** [comment]
Try this: https://codesandbox.io/embed/react-quill-demo-tn2x3?fontsize=14&hidenavigation=1&theme=dark

You just needed to import the css and the fix for mention is from issue #71

**Comment by a-utkarsh** [comment]
thanks got working!
