### ISSUE TITLE
Is there a way to add profile image to the mention search list ?

### ISSUE THREAD

**Issue by Dhrumilkp** [afry/quill-mention#164]
Is there a way to add profile image to mention search list...or any workarounds ?

**Comment by FrazeColder** [comment]
Push. Also interested in this. How can we modify the mention search list to add a profile image?

**Comment by MadSpindel** [comment]
Yes, you can use renderItem for that. What you need to do is the have something like "profileImageUrl" in the JSON search result, then in the renderItem create the HTML image with the url in item.profileImageUrl.

**Comment by FrazeColder** [comment]
@MadSpindel Can you please give us an exmaple on how do that?

I cannot find any example on the internet and just from your documentation I don't know how to do that.

**Comment by MadSpindel** [comment]
Sure, here is one quick example:
`var quill = new Quill("#editor", {
        placeholder: "Start by typing @ for mentions or # for hashtags...",
        modules: {
          mention: {
            allowedChars: /^[A-Za-z\sÅÄÖåäö]*$/,
            mentionDenotationChars: ["@", "#"],
            source: function(searchTerm, renderList, mentionChar) {
              let values;

              if (mentionChar === "@") {
                values = atValues;
              } else {
                values = hashValues;
              }

              if (searchTerm.length === 0) {
                renderList(values, searchTerm);
              } else {
                const matches = [];
                for (i = 0; i < values.length; i++)
                  if (
                    ~values[i].value
                      .toLowerCase()
                      .indexOf(searchTerm.toLowerCase())
                  )
                    matches.push(values[i]);
                renderList(matches, searchTerm);
              }
            },
            renderItem(item) {
              return `<img src="${item.profileImageUrl}">${item.value}`;
            },
          },
        },
      });`

You see renderItem? I added img src with item.profileImageUrl. You need to make sure each item in the JSON Object list from the source function (which is sent as matches to renderList) has a profileImageUrl value with the correct url.

**Comment by FrazeColder** [comment]
Since the PR [#341](https://github.com/quill-mention/quill-mention/pull/341) it is not possible to add a profile image to the list like above. We need to create [blots](https://github.com/quill-mention/quill-mention#mention-blot-styling).

Can anyone please help me out how to implement this with Vue/Nuxt3?
