### ISSUE TITLE
Cannot find module 'quill-mention/dist/quill.mention.css'

### ISSUE THREAD

**Issue by silviow** [afry/quill-mention#226]
Apparently newer versions of quill-mention do not include the "/dist/quill.mention.css'" file. Since some projects import this module, it is not possible to build these projects.

![quill-mention exception](https://user-images.githubusercontent.com/43392489/143445396-a74cf844-fc23-462a-9861-15555730c9cc.png)

To fix it, for now, you can lock the quill-mention version in your package.json. In particular, we are now using version 3.0.4 (because it includes the file).

![quill-mention](https://user-images.githubusercontent.com/43392489/143445426-eb8c1f11-1c97-4656-955d-8a1a91c3f214.png)

**Comment by MadSpindel** [comment]
Nice find. It looks like it created a new dist folder in the dist folder and put the quill.mention.css there, right? Not sure why that happened.

**Comment by MadSpindel** [comment]
Created a new version 3.0.6
