### ISSUE TITLE
Unexpected token: name (MentionBlot) - while building 

### ISSUE THREAD

**Issue by rut2** [afry/quill-mention#37]
ERROR in build.js from UglifyJs
Unexpected token: name (MentionBlot) [./~/quill-mention/src/blots/mention.js:6,0][build.js:121511,6]

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Quickscrum@1.0.0 build: `cross-env NODE_ENV=production webpack --progress --hide-modules`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the Quickscrum@1.0.0 build script 'cross-env NODE_ENV=production webpack --progress --hide-modules'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Quickscrum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production webpack --progress --hide-modules
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Quickscrum
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Quickscrum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\rut2\Quickscrum\Code\scrum-board\npm-debug.log

**Comment by MadSpindel** [comment]
Could you try if the new 2.2.1 version works better for you?
