### ISSUE TITLE
Duplicate of `ql-mention-list-container` in the DOM

### ISSUE THREAD

**Issue by twister124** [afry/quill-mention#38]
In my application I have a quill in separate component which I add after some event. Each time when I open/close this component `ql-mention-list-container` container is created, but previous container still is in the DOM.

You can try to reproduce it on you demo application by following steps:
1. Open demo application
2. Click on the logo(You will be redirected on the home page `https://afconsult.github.io`)
3. Click Back button

You need to have your developers took opened.
After this you will see that `ql-mention-list-container` is created one more time.

So question is, how to delete this container when we don't have quill on the page, and how to avoid duplications?

**Comment by arshDevslane** [comment]
I am also facing similar issue is there any solution for this ?
