### ISSUE TITLE
Unexpected token: name (Mention) - while building

### ISSUE THREAD

**Issue by bribar** [afry/quill-mention#50]
ERROR in 0.build.js from UglifyJs
Unexpected token: name (Mention) [./node_modules/quill-mention/src/quill.mention.js:7,0][0.build.js:24944,6]

ERROR in 1.build.js from UglifyJs
Unexpected token: name (Mention) [./node_modules/quill-mention/src/quill.mention.js:7,0][1.build.js:24944,6]

ERROR in 2.build.js from UglifyJs
Unexpected token: name (Mention) [./node_modules/quill-mention/src/quill.mention.js:7,0][2.build.js:23938,6]

Current version
"quill-mention": "^2.0.8"

Seems to build fine if I remove quill-mention. I tried some suggestions here https://github.com/webpack/webpack/issues/2972 but they didn't seem to help.

Any suggestions to get quill-mention to build?

**Comment by MadSpindel** [comment]
Have you tried if it works better with a later version?
