### ISSUE TITLE
Allow user to abort mention-action

### ISSUE THREAD

**Issue by silentsnooc** [afry/quill-mention#57]
I've noticed that it's possible to search for items which also contain whitespaces (which is cool) but sometimes a user just want to insert a denotation character and not search for anything. For this case it should be able to abort the mention-action by hitting <kbd>Esc</kbd>.

**Comment by andredewaard** [comment]
This works for me? The only problem when i add an @ and abort that action and try to mention someone a few lines further that mention will be added at the place i aborted that action before.
