### ISSUE TITLE
How to I add this to Vue.js?

### ISSUE THREAD

**Issue by apbln** [afry/quill-mention#62]

**Comment by JTInfinite** [comment]
use a vue-quill library and follow the instructions in this module. I am using quill-mention with vue-quill-editor and it works nicely.

**Comment by AousAnwar** [comment]
No need for vue-quill library, I had the same issue when I found this simple yet powerful article about [Wrapping Quill Editor in a Vue Component](https://pineco.de/wrapping-quill-editor-in-a-vue-component/), Quill-mention and other quill plugins work just as expected.
