### ISSUE TITLE
Caret sometimes gets stuck

### ISSUE THREAD

**Issue by Andkoo** [afry/quill-mention#65]
## Steps to reproduce

1. Mention some user

## Expected behavior

A space is added after the mention, the caret moves

## Actual behavior

`&nbsp;` isn't added after the mention. When the user presses space to add it manually, it's added to the DOM, but the caret doesn't move.

## Environment

• React 16.8.1
• Quill 1.3.6
• React-Quill 1.0.0
• Chrome 73
• macOS Mojave 10.14.3

## Additional info

• The bug is coming from the browser itself, not from your library or Quill. It's described here: [https://github.com/quilljs/quill/issues/1172](url). Basically `contenteditable="false"` inside `contenteditable="true"` is buggy.

**Comment by johnsonchau-bulb** [comment]
@Andkoo what fix was used to handle this? I'm currently facing this issue as well

**Comment by johnsonchau-bulb** [comment]
> @Andkoo what fix was used to handle this? I'm currently facing this issue as well

For those who might space this issue, using pre-wrap whitespace fixes it

https://github.com/quilljs/quill/issues/1960
