### ISSUE TITLE
Export configuration is broken, default export folder should be "dist" folder, now is "src' 

### ISSUE THREAD

**Issue by aacsinia** [afry/quill-mention#67]
Export configuration is broken, default export folder should be "dist" folder, now is "src' 

Configuration should look like:
{
  ....
  "files": [
    "dist",
    "LICENSE",
    "README.md"
  ],
...
}

**Comment by MadSpindel** [comment]
Do you have any links where I can read about it?

**Comment by MadSpindel** [comment]
This is fixed in the new 2.2.1 version.
