### ISSUE TITLE
Does not work with Node.js

### ISSUE THREAD

**Issue by mtimofiiv** [afry/quill-mention#70]
Probably not a huge use case for this but I need to render the resulting delta into plain HTML, and I would ideally like to do this server-side.

I'm using [nozer/quill-delta-to-html](https://github.com/nozer/quill-delta-to-html) to convert the base delta.

The current issue is that since it uses the `import` syntax it cannot really work in Node.js without something like Babel. So I cannot add this module in to render the mentions!

**Comment by MadSpindel** [comment]
Could you try if the new 2.2.1 version works better for you?

**Comment by mtimofiiv** [comment]
The import issue is resolved, thanks @MadSpindel. However there's a problem with using Quill itself in Node.js since it relies on `document`. But that's not really something you can fix in your module, right?
