### ISSUE TITLE
Unable to use mentions in IE11

### ISSUE THREAD

**Issue by northoutShiv** [afry/quill-mention#72]
Hi, 
I am using IE11 with quill packages-
ngx-quill": "^4.8.0",
"quill": "^1.3.6",
 "quill-mention": "^2.1.1"

but in IE 11, it is not working. Application is not loading.
I am using below example on my system with all the files installed mentioned in polyfills.ts

https://killercodemonkey.github.io/ngx-quill-example/

**Comment by suminc7** [comment]
Try this code
ReactQuill = require('react-quill')
window.Quill = ReactQuill.Quill
import('quill-mention/dist/quill.mention.min')

**Comment by MiRush94** [comment]
How to solve this with very same issue with angular8 and ie11? because neither of the examples work in ie11. you either see loading and nothing happens or you see nothing and nothing happens. No polyfill or browserslist or what so ever fixed the issue.

**Comment by kuba1** [comment]
I'm also trying to use quill-mention with ngx-quill and IE11 does not work. @northoutShiv, @MiRush94 were you able to resolve the issue?

**Comment by santoshprakash** [comment]
I'm also facing the same issue. Can someone help us
SCRIPT1002: Syntax error
"@angular/core": "^6.1.0",
"quill": "^1.3.6",
"quill-magic-url": "^1.0.3",
"quill-mention": "^2.2.5",
