### ISSUE TITLE
Package.json main entry point pointing to src instead of dist

### ISSUE THREAD

**Issue by JelleVisser** [afry/quill-mention#75]
Hi, I tried to use this module in IE11 and bumped into a couple of issues. Which I couldn't directly resolve on my own.

1. The main property in the package json is now directing to `"main": "src/quill.mention.js"`. I think the general convention here is to direct it to the post build files that would be located in the `dist` folder. The issue here is that the source files are using Ecmascript that is not supported by IE11. Where the distribution files should work since they are run through babel.

2. I manually changed the main property to direct to `dist/quil.mention.min.js`. The issue that I get then is `ReferenceError: Quill is not defined`.

Some more details:
- Angular 7.2.14
- Quill 1.3.6
- Ngx-quill 3.6.0
- Quill-mention 2.1.1

My current temporary solution is running babel over the source files manually and using those files from a forked repository.

Related issues:
#67 
#72

**Comment by MadSpindel** [comment]
This is fixed in the new 2.2.1 version.
